### ISSUE TITLE
Running on Linux

### ISSUE THREAD

**Issue by cindy-jth** [bordaigorl/rmview#141]
How would you set this up on Linux? I see installation files for Windows and Mac.

**Comment by bordaigorl** [comment]
You have two main options: with the manual istructions using `pip`, or using `docker`.
In both cases you would start by downloading the repository (the "Source code" link in Releases, or for the latest version the "Code > Download" green button on the main page).
The `pip` option should be the most straightforward, provided you don't have conflicting dependencies in your environment. To isolate dependencies you'd use `virtualenv` or `pyenv`.
The `docker` option isolates the dependencies very strongly since it builds a virtual machine.

**Comment by gimmy** [comment]
I have tried to install it with `pip`, but I receive this:

Using pip 22.2.2 from /home/gianmarco/.local/lib/python3.10/site-packages/pip (python 3.10)
[...]
  Traceback (most recent call last):
    File "/home/gianmarco/.local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/home/gianmarco/.local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/gianmarco/.local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in _get_build_requires
      self.run_setup()
    File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 267, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 33, in <module>
      setup(
    File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 148, in setup
      return run_commands(dist)
    File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 163, in run_commands
      dist.run_commands()
    File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 967, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
      cmd_obj.run()
    File "setup.py", line 30, in run
      genResources()
    File "setup.py", line 10, in genResources
      from PyQt5.pyrcc_main import main as pyrcc_main
    File "/tmp/pip-build-env-7fkkt55y/overlay/local/lib/python3.10/dist-packages/PyQt5/pyrcc_main.py", line 23, in <module>
      from .pyrcc import *
  ImportError: /tmp/pip-build-env-7fkkt55y/overlay/local/lib/python3.10/dist-packages/PyQt5/Qt5/lib/libQt5Xml.so.5: undefined symbol: _ZdlPvm, version Qt_5
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

Things seem to go smooth with Python 3.8 though. Is there some issue with Python 3.10 ?

**Comment by gimmy** [comment]
For other users experiencing the same issue: that was related to `pip`.
Upgrading `pip`with 
```
python3.10 -m pip install --upgrade pip
```
solved the problem.
