### ISSUE TITLE
Connection error with fw 2.15.0.1052

### ISSUE THREAD

**Issue by ldecicco** [bordaigorl/rmview#144]
As per subject rmview cannot connect to tablet after the latest update. This is the error I have:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/rmview/connection.py", line 178, in run
    self.client.connect(self.address, **self.options)
  File "/usr/local/lib/python3.9/site-packages/paramiko/client.py", line 406, in connect
    t.start_client(timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/paramiko/transport.py", line 699, in start_client
    raise e
  File "/usr/local/lib/python3.9/site-packages/paramiko/transport.py", line 2110, in run
    ptype, m = self.packetizer.read_message()
  File "/usr/local/lib/python3.9/site-packages/paramiko/packet.py", line 459, in read_message
    header = self.read_all(self.__block_size_in, check_rekey=True)
  File "/usr/local/lib/python3.9/site-packages/paramiko/packet.py", line 303, in read_all
    raise EOFError()`

Notice that:
* I am on Ubuntu latest version
* I have exactly the same error when running rmview in a Docker container
* I can successfully connect in ssh 
* reStream works

The issue looks to be due to paramiko. 
EDIT: 
I have enabled paramiko debug log level and got this:
`
DEB [20220930-17:22:46.691] thr=1   paramiko.transport: starting thread (client mode): 0x92e8f7f0
DEB [20220930-17:22:46.691] thr=1   paramiko.transport: Local version/idstring: SSH-2.0-paramiko_2.9.3
DEB [20220930-17:22:46.732] thr=1   paramiko.transport: Remote version/idstring: SSH-2.0-dropbear_2020.81
INF [20220930-17:22:46.732] thr=1   paramiko.transport: Connected (version 2.0, client dropbear_2020.81)
DEB [20220930-17:22:46.735] thr=1   paramiko.transport: === Key exchange possibilities ===
DEB [20220930-17:22:46.747] thr=1   paramiko.transport: kex algos: curve25519-sha256, curve25519-sha256@libssh.org, ecdh-sha2-nistp521, ecdh-sha2-nistp384, ecdh-sha2-nistp256, diffie-hellman-group14-sha256, kexguess2@matt.ucc.asn.au
DEB [20220930-17:22:46.747] thr=1   paramiko.transport: server key: ssh-ed25519, rsa-sha2-256, ssh-rsa
DEB [20220930-17:22:46.747] thr=1   paramiko.transport: client encrypt: chacha20-poly1305@openssh.com, aes128-ctr, aes256-ctr
DEB [20220930-17:22:46.748] thr=1   paramiko.transport: server encrypt: chacha20-poly1305@openssh.com, aes128-ctr, aes256-ctr
DEB [20220930-17:22:46.748] thr=1   paramiko.transport: client mac: hmac-sha1, hmac-sha2-256
DEB [20220930-17:22:46.748] thr=1   paramiko.transport: server mac: hmac-sha1, hmac-sha2-256
DEB [20220930-17:22:46.748] thr=1   paramiko.transport: client compress: zlib@openssh.com, none
DEB [20220930-17:22:46.748] thr=1   paramiko.transport: server compress: zlib@openssh.com, none
DEB [20220930-17:22:46.748] thr=1   paramiko.transport: client lang: <none>
DEB [20220930-17:22:46.748] thr=1   paramiko.transport: server lang: <none>
DEB [20220930-17:22:46.748] thr=1   paramiko.transport: kex follows: False
DEB [20220930-17:22:46.748] thr=1   paramiko.transport: === Key exchange agreements ===
DEB [20220930-17:22:46.748] thr=1   paramiko.transport: Kex: curve25519-sha256@libssh.org
DEB [20220930-17:22:46.748] thr=1   paramiko.transport: HostKey: ssh-rsa
DEB [20220930-17:22:46.749] thr=1   paramiko.transport: Cipher: aes128-ctr
DEB [20220930-17:22:46.749] thr=1   paramiko.transport: MAC: hmac-sha2-256
DEB [20220930-17:22:46.749] thr=1   paramiko.transport: Compression: none
DEB [20220930-17:22:46.749] thr=1   paramiko.transport: === End of kex handshake ===
DEB [20220930-17:22:46.755] thr=1   paramiko.transport: EOF in transport thread
`

**Comment by bordaigorl** [comment]
Looks like a Paramiko issue indeed.
Could you try downgrading paramiko to, say, 2.7.2?

**Comment by ldecicco** [comment]
Thanks for the suggestion. Unfortunately, I am still having issues with paramiko 2.7.2.

**Comment by bordaigorl** [comment]
I'm running rmview with paramiko at 2.11.0, I cannot reproduce your issue.
Do you mind sharing your configuration? (Please erase passwords or sensitive bits beforehand)
