### ISSUE TITLE
Screen stuck on "Connecting to reMarkable..." but red-dot is there, seems to be stuck on authentication

### ISSUE THREAD

**Issue by wulfdewolf** [bordaigorl/rmview#156]
I have a RM2, I've set backend to "screenshare".
When I connect rmview seems to be stuck on the connecting screen, although when I move my pencil across the screen the red-dot updates live.

I tried and succeeded to use rmview at home.
On 'eduroam' at university I can not seem to connect though.

Verbose output:
```
2023-09-20 17:37:37+0100 [-] Log opened.
[INFO] STARTING: Wed Sep 20 17:37:37 2023
[INFO] Searching configuration in rmview.json, /home/wolf/.config/rmview.json
[DEBUG] Configuration failure in rmview.json: [Errno 2] No such file or directory: 'rmview.json'
[INFO] Fetching configuration from /home/wolf/.config/rmview.json
[WARNING] Config file "/home/wolf/.config/rmview.json" is readable by others (permissions=664). If your config file contains secrets (e.g. password) you are strongly encouraged to make sure it's not readable by other users (chmod 600 /home/wolf/.config/rmview.json)
[DEBUG] Config values: {'ssh': {'address': '10.126.206.5', 'password': '**********', 'timeout': 2}, 'backend': 'screenshare', 'orientation': 'auto', 'pen_size': 15, 'pen_color': 'red', 'pen_trail': 200, 'background_color': 'white', 'hide_pen_on_press': True}
[INFO] Using known hosts file: /home/wolf/.config/rmview_known_hosts
[INFO] Loaded known hosts from /home/wolf/.config/rmview_known_hosts
[INFO] Connecting...
[INFO] Connected to 10.126.206.5
[INFO] Detected reMarkable 2.0
[INFO] Using backend 'screenshare'
[DEBUG] Stopping connection worker
[INFO] Connecting to ScreenShare, make sure you enable it
[WARNING] Authenticating, please wait...
2023-09-20 17:37:45+0100 [-] ChallengeReaderProtocol starting on 5901
2023-09-20 17:37:45+0100 [-] Starting protocol <rmview.screenstream.screenshare.ChallengeReaderProtocol object at 0x7f892a1fb370>
```

**Comment by bordaigorl** [comment]
Can you check if #146 helps (especially the newer comments)?

**Comment by wulfdewolf** [comment]
I had already implemented that fix when I experienced the same issues as #146 .
The issue must be related to something else.

**Comment by bordaigorl** [comment]
Sorry for getting back so late. Given rmview seems to work on some networks and not others this suggests it is a network configuration problem (see #111). I would not expect eduroam to let you use the necessary ports for authentication. I would suggest connecting to the tablet using a USB cable.

**Comment by ninaJay** [comment]
Hi, just chiming in with the same issue here using Version 3.9.3.1986. The ports are wide open, and it doesn't quite seem to be the same issue as https://github.com/bordaigorl/rmview/issues/146 but seems very similar in that it hangs when it's trying to get the config file from the rm.

**Comment by viktordimov** [comment]
I'm on 3.10.2.2063 
facing the same issue: can see the red dot while hovering the pen but can't actually see the screen, not on USB, not on Wi-Fi either.

**Comment by julienmartin31** [comment]
Same issue as viktordimov on 3.10.2.2063

**Comment by cgahr** [comment]
~I get the same error, I'm stuck on the connection screen but my pointer is working.~

~As far as I can tell, `/etc/version` contains the correct value.~

~I'm using rmview from nix, version `3.1.3`.~
<details>
<summary>Error message</summary>

```
[INFO] Connecting...
[INFO] Connected to 10.168.1.86
[INFO] Detected SW version: 3.12.4.4
[INFO] Detected device: reMarkable 2.0
[INFO] Using backend 'screenshare'
[INFO] Connecting to ScreenShare, make sure you enable it
[WARNING] Authenticating, please wait...
[INFO] received timestamp challenge 1720445236303
Unhandled Error
Traceback (most recent call last):
  File "/nix/store/mrkir0hi7jm5p7224wc0g1j84mzlv3nr-python3.12-twisted-24.3.0/lib/python3.12/site-packages/twisted/python/log.py", line 80, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/nix/store/mrkir0hi7jm5p7224wc0g1j84mzlv3nr-python3.12-twisted-24.3.0/lib/python3.12/site-packages/twisted/python/context.py", line 117, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/nix/store/mrkir0hi7jm5p7224wc0g1j84mzlv3nr-python3.12-twisted-24.3.0/lib/python3.12/site-packages/twisted/python/context.py", line 82, in callWithContext
    return func(*args, **kw)
  File "/nix/store/mrkir0hi7jm5p7224wc0g1j84mzlv3nr-python3.12-twisted-24.3.0/lib/python3.12/site-packages/twisted/internet/posixbase.py", line 482, in _doReadOrWrite
    why = selectable.doRead()
--- <exception caught here> ---
  File "/nix/store/mrkir0hi7jm5p7224wc0g1j84mzlv3nr-python3.12-twisted-24.3.0/lib/python3.12/site-packages/twisted/internet/udp.py", line 254, in doRead
    self.protocol.datagramReceived(data, addr)
  File "/nix/store/ripn778zvbinlc7nn2yvkxi9f96ypjks-rmview-3.1.3/lib/python3.12/site-packages/rmview/screenstream/screenshare.py", line 46, in datagramReceived
    if not self.callback(timestamp):
  File "/nix/store/ripn778zvbinlc7nn2yvkxi9f96ypjks-rmview-3.1.3/lib/python3.12/site-packages/rmview/screenstream/screenshare.py", line 119, in runVnc
    userId = self.get_userid()
  File "/nix/store/ripn778zvbinlc7nn2yvkxi9f96ypjks-rmview-3.1.3/lib/python3.12/site-packages/rmview/screenstream/screenshare.py", line 100, in get_userid
    with sftp.file('/etc/remarkable.conf') as f:
  File "/nix/store/qmb9qxdd45fvp2p8xg9gk6rqaapjn16d-python3.12-paramiko-3.4.0/lib/python3.12/site-packages/paramiko/sftp_client.py", line 372, in open
    t, msg = self._request(CMD_OPEN, filename, imode, attrblock)
  File "/nix/store/qmb9qxdd45fvp2p8xg9gk6rqaapjn16d-python3.12-paramiko-3.4.0/lib/python3.12/site-packages/paramiko/sftp_client.py", line 857, in _request
    return self._read_response(num)
  File "/nix/store/qmb9qxdd45fvp2p8xg9gk6rqaapjn16d-python3.12-paramiko-3.4.0/lib/python3.12/site-packages/paramiko/sftp_client.py", line 909, in _read_response
    self._convert_status(msg)
  File "/nix/store/qmb9qxdd45fvp2p8xg9gk6rqaapjn16d-python3.12-paramiko-3.4.0/lib/python3.12/site-packages/paramiko/sftp_client.py", line 938, in _convert_status
    raise IOError(errno.ENOENT, text)
builtins.FileNotFoundError: [Errno 2] No such file
```
</details>

EDIT: seems to be #161

**Comment by MrHappy** [comment]
I updated to 3.11.3.3 today and I'm stuck on this too.
Running on Arch (on Hyprland) - tried both aur-packages; both have same result.
Installing through pip gave me an error.
```
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
    python-xyz', where xyz is the package you are trying to
    install.

    If you wish to install a non-Arch-packaged Python package,
    create a virtual environment using 'python -m venv path/to/venv'.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.

    If you wish to install a non-Arch packaged Python application,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. Make sure you have python-pipx
    installed via pacman.
```

It used to work fine some time ago (last time I used was over a year ago) on v2.x.

**Comment by BHSPitMonkey** [comment]
This happened to me until I opened ports 5900 and 5901 to traffic from the reMarkable's IP address on my client machine (in my case, running Ubuntu with UFW enabled):

```
# Replace 192.168.1.x with your reMarkable's fixed IP, if you have one
sudo ufw allow from 192.168.1.x to any port 5900
sudo ufw allow from 192.168.1.x to any port 5901
```

I'm using the SSH tunnel option, though, so I'm not sure why this would be necessary.

@MrHappy - On newer versions of many distros, you need to follow from the error you quoted and set up a virtual environment for pip to run in. That can be simplified using certain tools, like `uv` (e.g. `uv venv; uv sync; uv pip install .; .venv/bin/rmview`)
