### ISSUE TITLE
Unable to screen share with os version 3.11.2.5

### ISSUE THREAD

**Issue by pretentious7** [bordaigorl/rmview#161]
I see the following error when attempting to screen share with the most recent remarkable update (v3.11.2.5)

```

2024-05-02 17:20:48-0400 [ChallengeReaderProtocol (UDP)] Unhandled Error
        Traceback (most recent call last):
          File "/gnu/store/sq79cvyszh7dr9v36sg1d9k8w97xck4v-profile/lib/python3.10/site-packages/twisted/python/log.py", line 86, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/gnu/store/sq79cvyszh7dr9v36sg1d9k8w97xck4v-profile/lib/python3.10/site-packages/twisted/python/context.py", line 122, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/gnu/store/sq79cvyszh7dr9v36sg1d9k8w97xck4v-profile/lib/python3.10/site-packages/twisted/python/context.py", line 85, in callWithContext
            return func(*args,**kw)
          File "/gnu/store/sq79cvyszh7dr9v36sg1d9k8w97xck4v-profile/lib/python3.10/site-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
            why = selectable.doRead()
        --- <exception caught here> ---
          File "/gnu/store/sq79cvyszh7dr9v36sg1d9k8w97xck4v-profile/lib/python3.10/site-packages/twisted/internet/udp.py", line 249, in doRead
            self.protocol.datagramReceived(data, addr)
          File "/home/abhishek/workbench/rmview/src/rmview/screenstream/screenshare.py", line 46, in datagramReceived
            if not self.callback(timestamp):
          File "/home/abhishek/workbench/rmview/src/rmview/screenstream/screenshare.py", line 119, in runVnc
            userId = self.get_userid()
          File "/home/abhishek/workbench/rmview/src/rmview/screenstream/screenshare.py", line 100, in get_userid
            with sftp.file('/etc/remarkable.conf') as f:
          File "/home/abhishek/.local/lib/python3.10/site-packages/paramiko/sftp_client.py", line 372, in open
            t, msg = self._request(CMD_OPEN, filename, imode, attrblock)
          File "/home/abhishek/.local/lib/python3.10/site-packages/paramiko/sftp_client.py", line 822, in _request
            return self._read_response(num)
          File "/home/abhishek/.local/lib/python3.10/site-packages/paramiko/sftp_client.py", line 874, in _read_response
            self._convert_status(msg)
          File "/home/abhishek/.local/lib/python3.10/site-packages/paramiko/sftp_client.py", line 903, in _convert_status
            raise IOError(errno.ENOENT, text)
        builtins.FileNotFoundError: [Errno 2] No such file

```

Going to investigate further this weekend.

**Comment by Lavode** [comment]
One of the on-device config files (formerly `/etc/remarkable.conf`) was moved to another location, leading to `rmview` failing to find it. There's a PR with initial work on fixing it here: https://github.com/bordaigorl/rmview/pull/159

**Comment by madanh** [comment]
I just symlinked the file and it worked!

**Comment by gladysz-piotr** [comment]
You can simply change the path to the "/home/root/.config/remarkable/xochitl.conf" in line 100 in screenshare.py 
It works for me.

**Comment by madanh** [comment]
UPDATE. Symlinking has to be done after every device update. Editing screenshare.py probably doesn't suffer from this.

**Comment by cgahr** [comment]
I can confirm that #159 fixes this issue. Can be closed.
